
var Pokedex = require('pokedex-promise-v2');
var P = new Pokedex();

// console.log(P)

var data = ['bulbasaur',
'ivysaur',
'venusaur',
'charmander',
'charmeleon',
'charizard',
'squirtle',
'wartortle',
'blastoise',
'caterpie',
'metapod',
'butterfree',
'weedle',
'kakuna',
'beedrill',
'pidgey',
'pidgiotto',
'pidgeot',
'ratatta',
'raticate',
'spearow',
'fearow',
'ekans',
'arbok',
'pikachu',
'sandshrew',
'sandslash']
data5 = ['nidoran',
'nidorina',
'nidoqueen',
'nidoran',
'nidorino',
'nidoking',
'celfairy',
'clefable',
'vulpix',
'ninetales',
'jigglypuff',
'wigglytuff',
'zubat',
'golbat',
'oddish',
'gloom',
'vileplume',
'paras',
'parasect',
'venonat',
'venomoth',
'diglett',
'dugtrio',
'meowth']
data4 = ['persian',
'psyduck',
'golduck',
'mankey',
'primeape',
'growlithe',
'arcanine',
'poliwag',
'poliwhril',
'poliwrath',
'abra',
'kadabra',
'alakazam',
'machop',
'machoke',
'machamp',
'bellsprout',
'weepinbell',
'victreebel',
'tentacool',
'tentacruel',
'geodude',
'graveler',
'golem',
'ponyta',
'rapidash']
data3 = ['slowpoke',
'slowbro',
'magnemite',
'magneton',
'farfetchd',
'doduo',
'dodrio',
'seel',
'dewgong',
'grimer',
'muk',
'shellder',
'cloyster',
'gastly',
'haunter',
'gengar',
'onix',
'drowzee',
'hypno',
'krabby',
'kingler',
'voltorb',
'electrode',
'exeggcute',
'exeggutor',
'cubone',
'marrowak',
'hitmonlee',
'hitmonchan',
'lickitung']
data2=[
'koffing',
'weezing',
'rhyhorn',
'rhydon',
'chansey',
'tangela',
'kangaskhan',
'horsea',
'seadra',
'goldeen',
'seaking',
'staryu',
'starmie',
'scyther',
'jynx',
'electabuzz',
'magmar',
'pinsir',
'tauros',
'magikarp',
'gyarados',
'lapras']
data1 =[
'ditto',
'eevee',
'vaporeon',
'jolteon',
'flareon',
'porygon',
'omanyte',
'omastar',
'kabuto',
'kabutops',
'aerodactyl',
'snorlax',
'articuno',
'zapdos',
'moltres',
'dratini',
'dragonair',
'dragonite',
'mewtwo',
'mew']


data.forEach(function(pokemon){
  P.getPokemonByName(pokemon)
  .then(function(response){
    console.log("['" + response.name + "'" + ",", "'" + response.sprites.front_default + "'" + ",", + response.base_experience + "]")
  })
 .catch(function(error) {
      console.log('There was an ERROR: ',pokemon);
    });
})

// data4.forEach(function(pokemon){
//   P.getPokemonByName(pokemon)
//   .then(function(response){
//     console.log("['" + response.name + "'" + ",", "'" + response.sprites.front_default + "'" + ",", + response.base_experience + "]")
//   })
//  .catch(function(error) {
//       console.log('There was an ERROR: ',pokemon);
//     });
// })


// P.getPokemonByName('rmime')
//   .then(function(response){
//     console.log(response.name, response.sprites.front_default)
//   })
//  .catch(function(error) {
//       console.log('There was an ERROR: ', error);
//     });

// ['bulbasaur',
// 'ivysaur',
// 'venusaur',
// 'charmander',
// 'charmeleon',
// 'charizard',
// 'squirtle',
// 'wartortle',
// 'blastoise',
// 'caterpie',
// 'metapod',
// 'butterfree',
// 'weedle',
// 'kakuna',
// 'beedrill',
// 'pidgey',
// 'pidgiotto',
// 'pidgeot',
// 'ratatta',
// 'raticate',
// 'spearow',
// 'fearow',
// 'ekans',
// 'arbok',
// 'pikachu',
// 'raichu',
// 'sandshrew',
// 'sandslash',
// 'nidoran',
// 'nidorina',
// 'nidoqueen',
// 'nidoran',
// 'nidorino',
// 'nidoking',
// 'celfairy',
// 'clefable',
// 'vulpix',
// 'ninetales',
// 'jigglypuff',
// 'wigglytuff',
// 'zubat',
// 'golbat',
// 'oddish',
// 'gloom',
// 'vileplume',
// 'paras',
// 'parasect',
// 'venonat',
// 'venomoth',
// 'diglett',
// 'dugtrio',
// 'meowth',
// 'persian',
// 'psyduck',
// 'golduck',
// 'mankey',
// 'primeape',
// 'growlithe',
// 'arcanine',
// 'poliwag',
// 'poliwhril',
// 'poliwrath',
// 'abra',
// 'kadabra',
// 'alakazam',
// 'machop',
// 'machoke',
// 'machamp',
// 'bellsprout',
// 'weepinbell',
// 'victreebel',
// 'tentacool',
// 'tentacruel',
// 'geodude',
// 'graveler',
// 'golem',
// 'ponyta',
// 'rapidash',
// 'slowpoke',
// 'slowbro',
// 'magnemite',
// 'magneton',
// 'farfetchd',
// 'doduo',
// 'dodrio',
// 'seel',
// 'dewgong',
// 'grimer',
// 'muk',
// 'shellder',
// 'cloyster',
// 'gastly',
// 'haunter',
// 'gengar',
// 'onix',
// 'drowzee',
// 'hypno',
// 'krabby',
// 'kingler',
// 'voltorb',
// 'electrode',
// 'exeggcute',
// 'exeggutor',
// 'cubone',
// 'marrowak',
// 'hitmonlee',
// 'hitmonchan',
// 'lickitung',
// 'koffing',
// 'weezing',
// 'rhyhorn',
// 'rhydon',
// 'chansey',
// 'tangela',
// 'kangaskhan',
// 'horsea',
// 'seadra',
// 'goldeen',
// 'seaking',
// 'staryu',
// 'starmie',
// 'scyther',
// 'jynx',
// 'electabuzz',
// 'magmar',
// 'pinsir',
// 'tauros',
// 'magikarp',
// 'gyarados',
// 'lapras',
// 'ditto',
// 'eevee',
// 'vaporeon',
// 'jolteon',
// 'flareon',
// 'porygon',
// 'omanyte',
// 'omastar',
// 'kabuto',
// 'kabutops',
// 'aerodactyl',
// 'snorlax',
// 'articuno',
// 'zapdos',
// 'moltres',
// 'dratini',
// 'dragonair',
// 'dragonite',
// 'mewtwo',
// 'mew']